version: 0.0
os: linux
files:
  - source: /build/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: server-scripts/install-httpd
      timeout: 300
      runas: root
    - location: server-scripts/start-server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server-scripts/stop-server
      timeout: 300
      runas: root

